"""
src/adapter_gemini.py
Google GenAI SDK implementation.
Focus: Async calls, Rate Limiting handling, Prompt Engineering for summaries.
"""

from __future__ import annotations

import json
from typing import TYPE_CHECKING

from google import genai
from tenacity import before_sleep_log, retry, stop_after_attempt, wait_exponential

from .config import settings
from .domain_models import WeeklyReport
from .ports import LLMEngine
from .utils_telemetry import logger

if TYPE_CHECKING:
    from datetime import date

from typing import cast

__all__ = ["GeminiAdapter"]


class GeminiAdapter(LLMEngine):
    def __init__(self):
        # Initialize Async Clients for load balancing / rate limit avoidance
        self.clients = [genai.Client(api_key=settings.GEMINI_API_KEY.get_secret_value()).aio]
        if settings.GEMINI_API_KEY_ALT:
            self.clients.append(genai.Client(api_key=settings.GEMINI_API_KEY_ALT.get_secret_value()).aio)
        self._current_index = 0

    def _get_client(self):
        client = self.clients[self._current_index]
        self._current_index = (self._current_index + 1) % len(self.clients)
        return client

    @retry(
        # Increased backoff for Gemini to avoid RPD limits
        wait=wait_exponential(multiplier=5, min=30, max=300),
        stop=stop_after_attempt(5),
        before_sleep=before_sleep_log(logger, 2),
    )
    async def generate_embedding(self, text: str) -> list[float]:
        try:
            # Truncate text if too long (rough safety check)
            safe_text = text[:9000]
            result = await self._get_client().models.embed_content(model=settings.MODEL_EMBEDDING, contents=safe_text)
            if result.embeddings and result.embeddings[0].values:
                return cast(list[float], result.embeddings[0].values)
            return []
        except Exception as e:
            # Check for Quota limits to log specifically
            if "429" in str(e) or "ResourceExhausted" in str(e):
                logger.warning("gemini_quota_limit_hit", error=str(e))
                # Tenacity will catch this and retry
            else:
                logger.error("gemini_embed_fail", error=str(e))
            raise

    @retry(
        wait=wait_exponential(multiplier=5, min=30, max=300),
        stop=stop_after_attempt(4),
        before_sleep=before_sleep_log(logger, 2),
    )
    async def summarize_daily(self, text: str) -> str:
        prompt = (
            "You are a professional news editor. Summarize the following news items into a "
            "concise Daily Briefing. Use HTML format (<ul>, <li>, <b>). "
            "Discard any promotional or irrelevant content. "
            "Focus on tech, AI, and global impact.\n\n"
            f"Content:\n{text[:20000]}"  # Soft limit
        )
        try:
            response = await self._get_client().models.generate_content(model=settings.MODEL_CHAT, contents=prompt)
            # Use safe text extraction
            if response.text:
                return response.text
            return "No summary generated by AI."
        except Exception as e:
            logger.error("gemini_sum_fail", error=str(e))
            return "<p>Error generating summary. Please check logs.</p>"

    @retry(
        wait=wait_exponential(multiplier=5, min=30, max=400),
        stop=stop_after_attempt(3),  # Report generation is expensive
        before_sleep=before_sleep_log(logger, 2),
    )
    async def generate_period_report(
        self, contexts: list[str], start_date: date, end_date: date, period_type: str = "Weekly"
    ) -> WeeklyReport:
        """
        Generates a summary for a given period (Weekly or Yearly).
        Adaptively handles context length.
        """
        # Combine contexts. For yearly reports, this might be huge.
        # Gemini 2.5 Flash handles ~1M tokens, so appending strings is usually safe up to ~700k words.
        # We put a hard character limit just in case.
        max_chars = 100000 if period_type == "Weekly" else 500000
        combined = "\n".join(contexts)[:max_chars]

        prompt = (
            f"Role: Senior News Editor. Task: Generate a {period_type} Report from {start_date} to {end_date}.\n"
            f"Source Data (Vectors Retrieval):\n{combined}\n\n"
            "Requirements:\n"
            "1. Deduplicate events.\n"
            "2. Identify the most significant trends.\n"
            "3. Output valid JSON.\n"
            "Schema: { 'summary_text': 'HTML string (<h2>Section</h2><p>...</p>)', 'key_events': ['Event 1', 'Event 2'] }"
        )

        try:
            response = await self._get_client().models.generate_content(
                model=settings.MODEL_CHAT,
                contents=prompt,
                config={"response_mime_type": "application/json"},
            )

            resp_text = response.text or "{}"
            data = json.loads(resp_text)

            return WeeklyReport(
                start_date=start_date,
                end_date=end_date,
                summary_text=data.get("summary_text", f"No {period_type} summary generated."),
                key_events=data.get("key_events", []),
                best_cover_image=None,
            )
        except Exception as e:
            logger.error("gemini_report_fail", period=period_type, error=str(e))
            raise
